name: Manual Semantic Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Cargo.toml version matches tag
        shell: pwsh
        run: |
          $TAG_VERSION="${{ github.ref_name }}"
          $CARGO_VERSION = (Select-String -Path Cargo.toml -Pattern '^version = "([^"]+)"').Matches.Groups[1].Value
          Write-Output "Tag version: $TAG_VERSION"
          Write-Output "Cargo.toml version: v$CARGO_VERSION"
          if ("v$CARGO_VERSION" -ne "$TAG_VERSION") {
            Write-Error "Error: Cargo.toml version ($CARGO_VERSION) does not match Git tag ($TAG_VERSION). Aborting release."
            exit 1
          }

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~\.cargo\registry
            ~\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Rust project
        run: cargo build --release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
         tag_name: ${{ github.ref_name }}
         name: Release ${{ github.ref_name }}
         draft: false
         prerelease: true
         files: |
           ./target/release/newpackagelister.exe
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
